// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace TheOmenDen.CrowsAgainstHumility.Data.Models;

public partial class Pack
{
    public Pack()
    {
        BlackCards = new HashSet<BlackCard>();
        WhiteCards = new HashSet<WhiteCard>();
    }

    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsOfficialPack { get; set; }
    public long ledger_start_transaction_id { get; set; }
    public long? ledger_end_transaction_id { get; set; }
    public long ledger_start_sequence_number { get; set; }
    public long? ledger_end_sequence_number { get; set; }

    public virtual ICollection<BlackCard> BlackCards { get; set; }
    public virtual ICollection<WhiteCard> WhiteCards { get; set; }
}