// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace TheOmenDen.CrowsAgainstHumility.Data.Models;

public partial class WhiteCard
{
    public Guid Id { get; set; }
    public string CardText { get; set; }
    public Guid PackId { get; set; }
    public long ledger_start_transaction_id { get; set; }
    public long? ledger_end_transaction_id { get; set; }
    public long ledger_start_sequence_number { get; set; }
    public long? ledger_end_sequence_number { get; set; }

    public virtual Pack Pack { get; set; }
}