// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace TheOmenDen.CrowsAgainstHumility.Data.Models;
public partial class fn_MultiFilterWordsForCardsResult
{
    public Guid Id { get; set; }
    public string CardText { get; set; }
    public Guid PackId { get; set; }
}
