// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace TheOmenDen.CrowsAgainstHumility.Core.Models;

public partial class Pack: IComparable<Pack>, IEquatable<Pack>
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsOfficialPack { get; set; }

    [NotMapped]
    public String OfficialPack => IsOfficialPack ? "Official" : String.Empty;

    [NotMapped] public Int32 WhiteCardsInPack => WhiteCards?.Count() ?? 0;

    [NotMapped] public Int32 BlackCardsInPack => BlackCards?.Count() ?? 0;

    public virtual IEnumerable<BlackCard> BlackCards { get; set; } = Enumerable.Empty<BlackCard>();
    public virtual IEnumerable<WhiteCard> WhiteCards { get; set; } = Enumerable.Empty<WhiteCard>();

    public int CompareTo(Pack other)
        => String.CompareOrdinal(Name, other.Name);

    public bool Equals(Pack other)
        => other is not null
           && Id == other.Id
           && Name == other.Name;

    public override bool Equals(object obj)
    {
        if (obj is null)
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }
        
        return obj is Pack other && Equals(other);
    }
    
    public override int GetHashCode()
    {
        return HashCode.Combine(Id, Name);
    }
}