// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace TheOmenDen.CrowsAgainstHumility.Core.Models;

public partial class Pack
{
    public Pack()
    {
        BlackCards = new HashSet<BlackCard>();
        WhiteCards = new HashSet<WhiteCard>();
    }

    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsOfficialPack { get; set; }

    [NotMapped]
    public String OfficialPack => IsOfficialPack ? "Official" : String.Empty;

    public virtual ICollection<BlackCard> BlackCards { get; set; }
    public virtual ICollection<WhiteCard> WhiteCards { get; set; }
}