// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace TheOmenDen.CrowsAgainstHumility.Core.Models;

public partial class Pack: IComparable<Pack>, IEquatable<Pack>
{
    public Pack()
    {
        BlackCards = new HashSet<BlackCard>();
        WhiteCards = new HashSet<WhiteCard>();
    }

    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsOfficialPack { get; set; }

    [NotMapped]
    public String OfficialPack => IsOfficialPack ? "Official" : String.Empty;

    public virtual ICollection<BlackCard> BlackCards { get; set; }
    public virtual ICollection<WhiteCard> WhiteCards { get; set; }

    public int CompareTo(Pack other)
        => String.CompareOrdinal(Name, other.Name);

    public bool Equals(Pack other)
        => other is not null
           && Id == other.Id
           && Name == other.Name;

    public override bool Equals(object obj)
    {
        if (obj is null)
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }
        
        return obj is Pack other && Equals(other);
    }
    
    public override int GetHashCode()
    {
        return HashCode.Combine(Id, Name);
    }
}