// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts.Configurations;

public partial class FilteredWhiteCardsByPackConfiguration : IEntityTypeConfiguration<FilteredWhiteCardsByPack>
{
    public void Configure(EntityTypeBuilder<FilteredWhiteCardsByPack> entity)
    {
        entity.HasNoKey();

        entity.ToView("vw_FilteredWhiteCardsByPack");

        entity.Property(e => e.CardText)
            .IsRequired()
            .HasMaxLength(1000);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<FilteredWhiteCardsByPack> entity);
}