// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using TheOmenDen.CrowsAgainstHumility.Core.DAO.Models.Cards;

namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts.Configurations;

public partial class PackConfiguration : IEntityTypeConfiguration<Pack>
{
    public void Configure(EntityTypeBuilder<Pack> entity)
    {
        entity.ToTable("Packs");

        entity.HasIndex(e => e.IsOfficialPack, "IX_Packs_IsOfficialPack");

        entity.HasIndex(e => e.Name, "IX_Packs_Name");

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(1000);

        entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(200);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Pack> entity);
}