// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts.Configurations;

public partial class WhiteCardConfiguration : IEntityTypeConfiguration<WhiteCard>
{
    public void Configure(EntityTypeBuilder<WhiteCard> entity)
    {
        entity.HasIndex(e => e.PackId, "IX_WhiteCards_PackId")
            .IncludeProperties(e => e.CardText);

        entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

        entity.Property(e => e.CardText)
            .IsRequired()
            .HasMaxLength(1000);

        entity.HasOne(d => d.Pack)
            .WithMany(p => p.WhiteCards)
            .HasForeignKey(d => d.PackId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_WhiteCards_Packs");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<WhiteCard> entity);
}