//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOmenDen.CrowsAgainstHumility.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOmenDen.CrowsAgainstHumility.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available White Cards cannot be changed when round is in progress..
        /// </summary>
        public static string CannotChangeAvailableWhiteCardsInProgress {
            get {
                return ResourceManager.GetString("CannotChangeAvailableWhiteCardsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Tsar is already set for the round..
        /// </summary>
        public static string CardTsarAlreadyExists {
            get {
                return ResourceManager.GetString("CardTsarAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization of Player List failed..
        /// </summary>
        public static string DeserializationFailed {
            get {
                return ResourceManager.GetString("DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Session ID provided..
        /// </summary>
        public static string InvalidSessionId {
            get {
                return ResourceManager.GetString("InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer duration must be greater than 0 seconds..
        /// </summary>
        public static string InvalidTimerDuration {
            get {
                return ResourceManager.GetString("InvalidTimerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player or Observer named &apos;{0}&apos; already exists in the player list..
        /// </summary>
        public static string PlayerAlreadyExists {
            get {
                return ResourceManager.GetString("PlayerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given player was not present in the round result..
        /// </summary>
        public static string PlayerNotInRoundResult {
            get {
                return ResourceManager.GetString("PlayerNotInRoundResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a new round when current round is already in progress..
        /// </summary>
        public static string RoundIsInProgress {
            get {
                return ResourceManager.GetString("RoundIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results of this round are read-only..
        /// </summary>
        public static string RoundResultIsReadOnly {
            get {
                return ResourceManager.GetString("RoundResultIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White card {0} is not available to the players..
        /// </summary>
        public static string WhiteCardIsNotAvailable {
            get {
                return ResourceManager.GetString("WhiteCardIsNotAvailable", resourceCulture);
            }
        }
    }
}
