// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using TheOmenDen.CrowsAgainstHumility.Core.DAO.Models.DbFunctionResults;

namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts;

public partial class CrowsAgainstHumilityContext
{
    [DbFunction("fn_MultiFilterWordsForCards", "dbo")]
    public IQueryable<fn_MultiFilterWordsForCardsResult> fn_MultiFilterWordsForCards(string FilteredWords)
    => FromExpression(() => fn_MultiFilterWordsForCards(FilteredWords));

    [DbFunction("fn_MultiFilterWordsForBlackCards", "dbo")]
    public IQueryable<fn_MultiFilterWordsForBlackCardsResult> fn_MultiFilterWordsForBlackCards(string FilteredWords)
    => FromExpression(() => fn_MultiFilterWordsForBlackCards(FilteredWords));

    protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<fn_MultiFilterWordsForCardsResult>().HasNoKey();
        modelBuilder.Entity<fn_MultiFilterWordsForBlackCardsResult>().HasNoKey();
    }
}