// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts
{
    public partial class CrowsAgainstHumilityContext : DbContext
    {
        public CrowsAgainstHumilityContext(DbContextOptions<CrowsAgainstHumilityContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BlackCard> BlackCards { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<WhiteCard> WhiteCards { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BlackCardConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PackConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WhiteCardConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
