// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using TheOmenDen.CrowsAgainstHumility.Data.Models;

namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts
{
    public partial class CrowsAgainstHumilityContext
    {

        [DbFunction("fn_MultiFilterWordsForCards", "dbo")]
        public IQueryable<fn_MultiFilterWordsForCardsResult> fn_MultiFilterWordsForCards(string FilteredWords)
        {
            return FromExpression(() => fn_MultiFilterWordsForCards(FilteredWords));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_MultiFilterWordsForCardsResult>().HasNoKey();
        }
    }
}
