// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using TheOmenDen.CrowsAgainstHumility.Data.Contexts.Configurations;
using TheOmenDen.CrowsAgainstHumility.Data.Models;
#nullable disable

namespace TheOmenDen.CrowsAgainstHumility.Data.Contexts
{
    public partial class CrowsAgainstHumilityContext : DbContext
    {
        public CrowsAgainstHumilityContext(DbContextOptions<CrowsAgainstHumilityContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BlackCard> BlackCards { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<WhiteCard> WhiteCards { get; set; }
        public virtual DbSet<FilteredWhiteCardsByPack> vw_FilteredWhiteCardsByPack { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BlackCardConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PackConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WhiteCardConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FilteredWhiteCardsByPackConfiguration());

            OnModelCreatingGeneratedFunctions(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
